tds-fdw/tds_fdw

- src/tds_fdw.c
If they don't, give an error of ERRCODE_FDW_INCONSISTENT_DESCRIPTOR_INFORMATION and
an appropriate error message.
Fixes issue #51
> Check that column counts of the TDS source and the PostgreSQL relation match

- tests/lib/tests.py
There was a problem in the way we caught exceptions at the test scripts, as postgres error attributes were used even when it was not possible (therefore masking exceptions).
See example at https://jenkins.juliogonzalez.es/job/tds_fdw-build/PG_VER=9.5,label=centos6/159/console
Now we show postgres error attributes if available, or just the error otherwise.
Tested at https://jenkins.juliogonzalez.es/job/tds_fdw-build-ng/PG_VER=9.5,label=centos6/1/console
> Fix problem with exceptions on tests: use postgres attributes only if available

- README.md
Some months ago I changed the main hostname for Jenkins to jenkins.juliogonzalez.es, so it's easier to migrate it outside OpenShift at some point (if needed) without breaking all the associated projects.
For tds_fdw this is the first step (next will be to change the hooks).
> Change build status badge hostname to jenkins.juliogonzalez.es

- README.md
Curiously there's no link in the readme to Installing on OSX.  If merged, this pull request rectifies this.
> Add a link to Installing on OSX.

- InstallCentOS.md
- InstallOSX.md
- InstallUbuntu.md
- README.md
The docs still refer to `https://github.com/GeoffMontee/tds_fdw`.  It appears this repo has since been moved. 
If merged, the docs now say `https://github.com/tds-fdw/tds_fdw` thus eliminating one potential source of confusion.
> Repointer the docs to tds-fdw/tds_fdw.

- Makefile
- include/visibility.h
- src/tds_fdw.c
Note: this implementation is probably not portable. Suggestions on how to make it so are welcome.
Symbol deparseSelectSql() is used in both postgres_fdw and tds_fdw. This
symbol is exported as a global symbol in both cases as is the default
behavior for non-static functions. When tds_fdw.so is loaded before
postgres_fdw.so linker will link the implementation from tds_fdw into
postgres_fdw, causing segfaults when postgres_fdw is used.
Because there is no reason to actually export these functions this patch
adjusts build flags to default functions to non-exported and overrides
PostgreSQL PGDLLEXPORT definition to mark functions as exported. As
PG_FUNCTION_INFO_V1 does not add export flag to the actual function
declaration we need to manually annotate the exported functions.
An alternative …
> Remove unnecessary symbol visibility to eliminate conflict with postgres_fdw

- src/tds_fdw.c
- tests/tests/mssql/000_create_schema.sql
Even for non case sensitive databases, the schema and its views are always uppercase.
See #146, will fix it pending new version (alpha2) generation.
> Fix problem accessing INFORMATION_SCHEMA views on case sensitive databases

- tests/lib/tests.py
Cleanup versions retrieved from PostgreSQL/MSSQL servers to avoid problems.
For example Ubuntu decided to add their own versioning starting with PostgreSQL `10.2: 10.2 (Ubuntu 10.2-1.pgdg14.04+1` instead of `10.2`
This fixes the problems we were having with Ubuntu and PostgreSQL 10 for the last days.
**Tested:** https://jenkins.juliogonzalez.es/job/tds_fdw-build-free/52/
> Improve PostgreSQL version detection

- src/deparse.c
From https://www.postgresql.org/docs/8.2/static/functions-matching.html:
The operator ~~ is equivalent to LIKE, and \~~* corresponds to ILIKE.
There are also !~~ and !~~* operators that represent NOT LIKE and NOT ILIKE, respectively. All of these operators are PostgreSQL-specific.
> Fix the Problem with like. Solution from User ale2317 (see Issue #118).

- src/tds_fdw.c
All uniqueidentifiers from SqlServer are imported as text (default path). Change this to uuid.
> Import SqlServer datatype uniqueidentifier as postgres uuid.

- .gitignore
- include/tds_fdw.h
- src/deparse.c
- src/tds_fdw.c
- PostgreSQL commit 8237f27b504ff1d1e2da7ae4c81a7f72ea0e0e3e
This v11 commit removed "get_relid_attribute_name", the
replacement is "get_attname" with a third argument "false".
- PostgreSQL commit 9fa6f00b1308dd10da4eca2f31ccbfc7b35bb461
This v11 commit removed the individual size parameters for
AllocSetContextCreate (which is now a macro) and foced usage
of the ALLOCSET_DEFAULT_SIZES macro (which in turn did not exist
before 9.6).
- PostgreSQL commit c6293249dc178f52dd508c3e6ff353af41c90b58
This v11 commit changed the internal representation of a tuple
descriptor. You now have to use the "TupleDescAttr" macro to
access the individual attributes.
In passing, add a ".gitignore" file.
> Adapt to core API changes

- ForeignServerCreation.md
- src/tds_fdw.c
This is useful for automatic fail-over to a secondary server.
For this we have to introduce a new error handler that captures
connection errors, but does not throw an error.
The last captured error is thrown if all servers fail.
> Allow a comma separated list for "servername"

- src/tds_fdw.c
I don't think that it really can happen that "dbproc" is NULL
without an error message (and hence the ereport around
line 586 is probably dead code), but let's be safe.
> Clear the error message in the right spot

- InstallCentOS.md
It seems that the official PostgreSQL Yum packages from the development group now come with JIT enabled by default, and requiring `clang` from LLVM7.
This change explains how to get it, so builds can happen again for CentOS7.
Fixes #192 
Related: #182
> Fix instructions for CentOS7

- InstallCentOS.md
1. We now have a Yum repository with RPMs for releases starting at `2.0.0-alpha3`
2. The packages are generated with the SPECs and scripts at https://github.com/tds-fdw/rpm
Since this is a big rewrite, maybe it's best having a look at the rendered file:
https://github.com/juliogonzalez/tds_fdw/blob/44ea5c80682c7ed151f6f420a06c63b557c331bd/InstallCentOS.md
> Rewrite instructions for CentOS, including new Yum repository

- InstallOSX.md
- Makefile
@juliogonzalez Hi, this is my try. It goes a bit further than your pull request #198 e.g. I noticed that the instruction of how to start the Postgres Server don't apply to macOS. So I fixed that, too.
At first, I considered OS detection in the Makefile, but that actually didn't solve our underlying problem in case other package managers (MacPorts,...) are used. So I left that for when it's needed. 
Fixes #197
> Improve OSX install

- InstallopenSUSE.md
- README.md
openSUSE Leap 42.3 is now EoL, so instructions are changed to 15.1 (which has PostgreSQL 9.6 and 10, so we use the occasion to use 10.X for the example)
I am also fixing the capitalization. The correct name is `openSUSE` and not `OpenSUSE`.
> Change mentions from openSUSE Leap 42.3 to 15.1 and use correct capitalization

- src/deparse.c
- src/tds_fdw.c
This patch allows use of tds_fdw with PG12.
This implies #211 observations :
* `ArrayRef` was changed to  `SubscriptingRef`
* `ExecStoreTuple` was split into two functions due to Pluggable storage engine
* Includes layout have changed
This patch was tested against PG 12 RC1 on a centos/7 with pgdg source. It may also still work on older version of PG as all changes were protected by preoprocessor instructions.
> Add PostgreSQL 12 support w/ new types+ExecTuple func

- README.md
- tests/README.md
- tests/lib/messages.py
- tests/lib/tests.py
- tests/mssql-tests.py
- tests/postgresql-tests.py
- tests/tests/postgresql/001_create_server.sql
`--debugging` display PostgreSQL backend PID and waits for key to be pressed allowing `gdb --pid=<PID>` for debugging purpose (in another session). It also prints the SQL sentences being executed and displays display more precise informations on test crash location using `psycopg2.extensions.Diagnostics` class
`--unattended-debugging` does almost the same as `debugging`, but it doesn't pause, and writes the PostgreSQL logs to console.
`--tds_version` allows to specify tds version at test time (both in mssql testing and pgsql testing)
This PR will also now print PostgreSQL logs if there are errors.
> Add `--debugging`, `--unattended-debugging` and  `--tds_version` parameters

- InstallAlpine.md
- InstallCentOS.md
- InstallDebian.md
- InstallUbuntu.md
- InstallopenSUSE.md
Improvements:
- Add build dependencies
- Do not depend on `lsb_release` for CentOS/Ubuntu, as it's not available at Docker images (and maybe not at minimal installations)
- Point to the most recent released tds_fdw version (`v2.0.0-alpha.3`) where appropriate (older versions are not working anymore with current supported PostgreSQL versions).
- Remove the references to master not working at Debian, as I can't reproduce the issue (https://github.com/tds-fdw/tds_fdw/issues/230#issuecomment-555720943)
- Make all instructions similar in terms of structure (where possible, CentOS requires some extra parts, and Alpine has a Dockerfile as a bonus)
**BIG EXCEPTION:** I didn't update MacOS instructions as I don't have one to validate them.
> Update doc to recent OS and PostgreSQL versions and several improvements

- src/tds_fdw.c
`tdsEndForeignScan` tries to free the query string, but is just a
pointer into the `ForeignScanState` we got passed in `tdsBeginForeignScan`.
We have no business to free that memory, which is allocated in
`PortalContext` by the traffic cop and freed when the portal is done.
This leads to intermittent crashes when the `pfree` segfaults.
Here is a stack trace from such a crash seen by a customer:
```none
Core was generated by `postgres: fhin primuss_fhin app-in.primuss.rrze'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  pfree (pointer=0x5569ec064258) at mcxt.c:1060
#1  0x00007f11188fbd83 in tdsEndForeignScan (node=<optimized out>) at src/tds_fdw.c:1931
#2  0x00005569eb162d93 in ExecEndForeignScan (node=0x5569ec06c028) at nodeForeignscan.c:249
#3  0x00005569eb151b21 in …
```
> Remove bad pfree of query string

- README.md
- src/tds_fdw.c
There is already a `tdsExplainForeignScan`, but it does nothing.
I think seeing the remote query would make debugging easier.
> EXPLAIN (VERBOSE) shows remote query

- src/tds_fdw.c
- tests/tests/postgresql/035_rescan.json
- tests/tests/postgresql/035_rescan.sql
The implementation of that function was left empty, but that
can lead to wrong query results: If the foreign scan is on
the inner side of a nested loop join, the order of function
calls is as follows:
tdsBeginForeignScan
tdsIterateForeignScan  (until done)
tdsReScanForeignScan   (prepare for second loop iteration)
tdsIterateForeignScan  (until done)
...                    (repeat the last two for each loop)
tdsEndForeignScan
Since "tdsReScanForeignScan" didn't do anything, the second
and all following scans will not return any rows, since the
result set is already exhausted.
This leads to wrong query results.
To fix, consume any remaining rows and reset the state.
> Fix tdsReScanForeignScan to actually work

- tests/lib/tests.py
Working at https://jenkins.juliogonzalez.es/job/tds_fdw-build-free/17/ (Ubuntu 20.04 images are using Python 3).
When this is merged, the CI will be readjusted to use Ubuntu 20.04 instead of Ubuntu 18.04.
Fixes https://github.com/tds-fdw/tds_fdw/issues/284
> Make the test scripts compatible with Python 3

- src/deparse.c
Dummy relabeling seems to be an internal postgres mechanism to handle casting between two binary-compatible datatypes.
I ran into an issue while using a condition on a varchar column coerced to text.
Without this fix, this postgres query
`SELECT ... FROM ... WHERE this_col_is_a_varchar::text ~~ 'burp%';`
generates something like
`SELECT ... FROM ... WHERE this_vol_is_a_varchar as text like 'burp%';`
which triggers a syntax error. I'm pretty sure passing this relabeling mechanism along is not necessary.
See https://github.com/postgres/postgres/blob/845cad4d51cb12a34ea012dfe58af5ef490384fc/src/include/nodes/primnodes.h#L837
> Do not pass dummy relabeling to foreign server

- src/options.c
Previously, the code applying default settings would assume the option was unset, and set the default value of 1. We use a sentinel value instead, which allows us to detect this case separately.
> Allow use_remote_estimate to be set to 0.

- src/tds_fdw.c
Previously, queries could not be cancelled.
> Support query cancellation using FreeTDS's cancellation hooks.

- Makefile
- tds_fdw--2.0.1--2.0.2.sql
- tds_fdw--2.0.2--2.0.3.sql
Fix for the ability to upgrade from version 2.0.1 to 2.0.3
Update from version 1.0.0 intentionally skipped
> add upgrade route from 2.0.1 to 2.0.3 

- src/tds_fdw.c
Hi, Postgres 17 Beta1 is out and I noticed tds_fdw doesn't build with it due to the change mentioned in the title, so I thought I'd submit a PR for it. 
(Following is the commit message)
The upstream commit adds a new argument to create_foreignscan_path [1]. tds_fdw doesn't currently replace joins, so nothing is passed to the new argument.
[1] https://github.com/postgres/postgres/commit/9e9931d2bf
> Update create_foreignscan_path parameters for PostgreSQL commit 9e9931d2bf

- InstallRHELandClones.md
The [CI started failing for Rocky Linux 8 on August 9th](https://jenkins.juliogonzalez.es/job/tds_fdw-build/3236/console) as `/usr/bin/clang` was not installed. I tried installing from scratch and more packages were missing besides `clang` (`llvm` and `redhat-rpm-config`, this one at least on containers).
Since `gcc` is a requirement for `clang`,  we don't need to specify it.
So this PR is basically implementing at the doc, the following changes at the images: https://github.com/tds-fdw/ci-setup/compare/b3d2ac6ec21bf899c6ea56d6b6aed47e8727cb7a...399c0df2073872242404818b2dcdae3c7538ab65
With that, the extension builds and the test are able to run: https://jenkins.juliogonzalez.es/view/tds_fdw-jobs/job/tds_fdw-build/3243/
I am not sure why this is suddenly happening, I guess it's a change …
> Update RHEL and Clones compilation instructions

- src/tds_fdw.c
In the current implementation, attempting to select from tables that have fields with the `money` datatype adds commas which break the double type
SELECT * FROM "vadmin_dbo"."accounts" LIMIT 1
Bad value for type double : 10,000,000.00
> Update tds_fdw.c - money to decimal

- tests/tests/mssql/030_create_money_min_table.json
- tests/tests/mssql/030_create_money_min_table.sql
- tests/tests/mssql/031_create_money_max_table.json
- tests/tests/mssql/031_create_money_max_table.sql
- tests/tests/mssql/032_create_smallmoney_min_table.json
- tests/tests/mssql/032_create_smallmoney_min_table.sql
- tests/tests/mssql/033_create_smallmoney_max_table.json
- tests/tests/mssql/033_create_smallmoney_max_table.sql
- tests/tests/postgresql/036_moneymin.json
- tests/tests/postgresql/036_moneymin.sql
- tests/tests/postgresql/037_moneymax.json
- tests/tests/postgresql/037_moneymax.sql
- tests/tests/postgresql/038_smallmoneymin.json
- tests/tests/postgresql/038_smallmoneymin.sql
- tests/tests/postgresql/039_smallmoneymax.json
- tests/tests/postgresql/039_smallmoneymax.sql
- Fixes https://github.com/tds-fdw/tds_fdw/issues/375
- Hopefully completes https://github.com/tds-fdw/tds_fdw/pull/374
As usual, we text the min and max value for each type. Those are created a separate tables at MSSQL, then we map them as foreign tables at PostgreSQL and we try to read the values.
https://github.com/tds-fdw/tds_fdw/pull/374 does a conversion to decimal and seems that works, even when we map directly to money.
I see @Daemach tried to use the automated mapping, so not sure if he ever tried to do manual mapping of the data types (so far we don't have a test for this, IIRC).
> Tests for the money and smallmoney types

- include/tds_fdw.h
- src/deparse.c
- src/tds_fdw.c
This commit copes with upstream commit 8123e91f5 with pathkey changes, ExplainState relocations in c65bc2e1d, and the disabled nodes parameter in e222534679.
This should resolve https://github.com/tds-fdw/tds_fdw/issues/384
It's mostly the same as the patch referenced in-thread but converted to use preprocessor defs to stay backward compatible as is done in the code already.
> Support PostgreSQL 18

- InstallAlpine.md
- InstallDebian.md
- InstallOSX.md
- InstallRHELandClones.md
- InstallUbuntu.md
- InstallopenSUSE.md
- META.json
- Makefile
- tds_fdw--2.0.4--2.0.5.sql
- tds_fdw.control
A new release for PostgreSQL 18 was requested via: https://github.com/tds-fdw/tds_fdw/issues/384
> Release 2.0.5 to prepare for PostgreSQL 18
