- src/tds_fdw.c
- reorder tdsGetColumnMetadata() to set festate->attinmeta
earlier; move the check for column count mismatch accordingly
- palloc() festate->columns and festate->datums with Postgres'
column count (attinmeta->tupdesc->natts) instead of the source
column count (festate->ncols), as they are passed to
heap_form_tuple() and thus must be of matching size
- for columns that exist in Postgres but not in the source,
set festate->isnull[] so the invalid Datum is not used
(avoids potential segfault, see Issue #51)
> fix mismatch handling with match_column_names

- src/tds_fdw.c
I think I found basically two things to remove some unneeded code blocks, to improve readability. See the commit message for details.
I'm not familiar with the PostgreSQL APIs, so I'm only going by documentation and may be wrong about this. So please treat this more as an idea ;-)
> minor cleanups

- tests/tests/mssql/025_create_match_column_table.sql
- tests/tests/postgresql/027_column_match_enabled.sql
- tests/tests/postgresql/028_column_match_disabled.sql
Checks for a36cf02, 6d01ba9 and 28b9dcc
Tested and working at https://jenkins.juliogonzalez.es/job/tds_fdw-build-ng/5/
> Add tests for column matching

- src/tds_fdw.c
Hi,
Can you please review my changes that fix the compilation errors for PostgreSQL 9.6? If all looks good can these changes be please merged into master?
Thanks,
Sravan
> Fix compilation errors with PostgreSQL 9.6

- InstallOSX.md
They're very similar to Ubuntu, only changing the freetds dependency
installation.
> Add installation instructions for OSX

- src/tds_fdw.c
Hello,
This pull request solves the issue #104.
It seems that there is not schemas in SAP ASE. So `IMPORT FOREIGN SCHEMA` imports tables of specific owner. So for SAP ASE table owner is equal to schema.
If you have notes about this I will fix it.
> Implement IMPORT FOREIGN SCHEMA that supports Sybase

- src/tds_fdw.c
Hello,
I fixed the syntax typo. Also fixed the algorithm, which determines if we import from MS SQL Server or from Sybase.
> Fix IMPORT FOREIGN SCHEMA for Sybase. Fixed syntax error and server version checking

- src/deparse.c
Hi Geoff,
I just searched for "::" in deparse.c and replaced all remaining instances with the appropriate MS SQL server syntax for use in the CAST(...as ..) form that was begun earlier.
This fixes a few things, notably complex joins, where the printRemotePlaceholder method is called.
All my queries work with the patched code. YMMV.
Thank you so much for your work on this!
-Shane
> Replace all double-colon casting with CAST(...as )

- InstallOpenSUSE.md
- README.md
Tested locally on a Docker container.
> Document installation on OpenSUSE Leap 42.3

- README.md
See https://github.com/juliogonzalez/tds_fdw/blob/build-status/README.md#build-status
Related: #144
> Replace build status with a build status matrix

- InstallAlpine.md
Added Alpine Linux and example Dockerfile for Docker based installs.
> Added Alpine (and Docker) install instructions

- tests/README.md
Part of the fix for https://github.com/tds-fdw/tds_fdw/issues/223
Ping @jcarnu, can you have a look?
> Add doc about how to add or modify tests

- InstallAlpine.md
- InstallCentOS.md
- InstallOSX.md
- InstallUbuntu.md
- InstallopenSUSE.md
> Specify how to specify a PostgreSQL version when several are available

- tests/lib/tests.py
> Fix typo at the testing version check

- InstallDebian.md
- README.md
I am quite new to git world.
It's ok to make the pull request from a branch on my repo different from "master", or should I merge on my repo and then submit the pull request from master to master?
> Added a MarkDown file for installing instructions on Debian

- src/tds_fdw.c
Simple fix for no table in schema error found in #219 and #210.  WIP on sys/information_schema extract for columns and views/tables. (will create another branch)
> Fix import schema with no table check, no tested yet

- InstallUbuntu.md
Extension needed to prevent 404 Not Found in wget call
> Added .tar extension to wget command

- README.md
> Hint about encrypted connections to MSSQL

- src/tds_fdw.c
- tests/tests/mssql/028_create_view_simple_prerequisites.json
- tests/tests/mssql/028_create_view_simple_prerequisites.sql
- tests/tests/mssql/029_create_view_simple.json
- tests/tests/mssql/029_create_view_simple.sql
- tests/tests/postgresql/033_view_simple.json
- tests/tests/postgresql/033_view_simple.sql
Fixes #178
Replaces #233 as this PR adds tests on top.
> Extend Import Foreign Schema to Views

- src/tds_fdw.c
This PR does for Sybase DB what #248 did for MS SQL Server.
> Extend IMPORT FOREIGN SCHEMA for Sybase to Views

- .github/ISSUE_TEMPLATE.md
Let's try to make things easier for bug reports.
With this, they won't need to remember about how to create code/log blocks.
> Improve the issue template

- tests/tests/postgresql/034_explain.json
- tests/tests/postgresql/034_explain.sql
> Add tests for EXPLAIN (VERBOSE)

- tests/README.md
- tests/validate-test-json
For now it needs to run locally, but we could always add a GitHub action in the future :-)
Fixes https://github.com/tds-fdw/tds_fdw/issues/223
> Add a validator for the JSON files for tests

- src/deparse.c
> postgresql 15 support

- InstallAlpine.md
- InstallDebian.md
- InstallOSX.md
- InstallRHELandClones.md
- InstallUbuntu.md
- InstallopenSUSE.md
- META.json
- tds_fdw.control
Fixes #316 and fixes #305
After this PR is merged, a new GitHub release will be needed.
> Bump version to 2.0.3

- src/deparse.c
> change pg type to tds type

- src/tds_fdw.c
> Fix importing from Sybase schema (float fields)

- InstallAlpine.md
- InstallDebian.md
- InstallOSX.md
- InstallRHELandClones.md
- InstallUbuntu.md
- InstallopenSUSE.md
- META.json
- Makefile
- tds_fdw--2.0.3--2.0.4.sql
- tds_fdw.control
> Issue #364: Release 2.0.4 to prepare for PostgreSQL 17
